#!/bin/sh
#
# Copyright (c) 2012 Breno Ramalho Lemes <breno@br-lemes.net>
# http://www.br-lemes.net/
#
# Verifica o status da conexão de internet, o IP e o tempo conectado do meu
# roteador wireless Smart Lan APRIO150. 
#
# Histórico:
#
# 27-04-2012 * Versão inicial.
#
# Licença: WTFPL
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.
#

# Este é o IP padrão para este modelo de roteador
status="http://192.168.1.254/cgi-bin/status/"

lynx -source "$status" | grep 'name="WAN_LINK_STATUS"' | cut -d = -f 4 | cut -d \" -f 2
lynx -source "$status" | grep 'name="WAN_IP_ADDR"' | cut -d = -f 4 | cut -d \" -f 2
conn_time=$(lynx -source "$status" | grep 'name="INTERNET_CONN_TIME"' | cut -d = -f 4 | cut -d \" -f 2)
day=$((($conn_time - $conn_time % 86400) / 86400))
conn_time=$(($conn_time - $day * 86400))
hr=$((($conn_time - $conn_time % 3600) / 3600))
conn_time=$(($conn_time - $hr * 3600))
min=$((($conn_time - $conn_time % 60) / 60))
sec=$(($conn_time - $min * 60))
printf "%d dia(s) %d hora(s) %d minuto(s) %d segundo(s)\n" $day $hr $min $sec
