#!/bin/sh
#
# Copyright (c) 2012,14 Breno Ramalho Lemes <breno@br-lemes.net>
# http://www.br-lemes.net/
#
# Verifica o status da conexão de internet, o IP e o tempo conectado do meu
# roteador wireless Smart Lan APRIO150. 
#
# Histórico:
#
# 27-04-2012 * Versão inicial.
# 10-07-2014 * IP do roteador na variável de ambiente $SMARTLAN
#
# Licença: WTFPL
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.
#

# Este é o IP padrão para este modelo de roteador
[ -z "$SMARTLAN" ] && SMARTLAN="192.168.1.254"
statusurl="http://$SMARTLAN/cgi-bin/status/"

source=$(lynx -source "$statusurl" 2> /dev/null)
[ "$?" != "0" ] && exit 1
eval $(echo "$source" | grep '\(name="WAN_LINK_STATUS"\|name="WAN_IP_ADDR"\|name="INTERNET_CONN_TIME"\)' | sed 's/^.*name="//;s/" value=/=/;s/>.*$//')
echo "$WAN_LINK_STATUS"
echo "$WAN_IP_ADDR"
day=$((($INTERNET_CONN_TIME - $INTERNET_CONN_TIME % 86400) / 86400))
INTERNET_CONN_TIME=$(($INTERNET_CONN_TIME - $day * 86400))
hr=$((($INTERNET_CONN_TIME - $INTERNET_CONN_TIME % 3600) / 3600))
INTERNET_CONN_TIME=$(($INTERNET_CONN_TIME - $hr * 3600))
min=$((($INTERNET_CONN_TIME - $INTERNET_CONN_TIME % 60) / 60))
sec=$(($INTERNET_CONN_TIME - $min * 60))
printf "%d dia(s) %d hora(s) %d minuto(s) %d segundo(s)\n" $day $hr $min $sec
